CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_3B80D832_EDBF_4FBC_88F9_AC6B9A4381D2" START WITH 1 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "PUBLIC"."PHONE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_3B80D832_EDBF_4FBC_88F9_AC6B9A4381D2" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_3B80D832_EDBF_4FBC_88F9_AC6B9A4381D2",
    "CITY_CODE" VARCHAR(255) NOT NULL,
    "COUNTRY_CODE" VARCHAR(255) NOT NULL,
    "NUMBER" VARCHAR(255) NOT NULL,
    "ID_USERS" BINARY
);
ALTER TABLE "PUBLIC"."PHONE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PHONE;
CREATE MEMORY TABLE "PUBLIC"."USER"(
    "ID" BINARY NOT NULL,
    "ACTIVE" BOOLEAN NOT NULL,
    "CREATED" TIMESTAMP NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL,
    "LAST_LOGIN" TIMESTAMP NOT NULL,
    "LAST_TOKEN" VARCHAR(2000) NOT NULL,
    "MODIFIED" TIMESTAMP NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;
ALTER TABLE "PUBLIC"."PHONE" ADD CONSTRAINT "PUBLIC"."FK8M1WYLWGSDD2LQHU9GYJ74HM2" FOREIGN KEY("ID_USERS") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;